common/models/TiktokAccount.php
<?php

namespace common\models;

use backend\services\ActionManager;
use Yii;
use yii\db\ActiveRecord;


/**
 * This is the model class for table "tiktok_account".
 *
 * @property int $id
 * @property string $nickname
 * @property string|null $url
 * @property string|null $uuid
 * @property string|null $secure_id
 * @property string|null $tiktok_id
 * @property string $email
 * @property string|null $device_id
 * @property string|null $fp
 * @property string|null $iid
 * @property string|null $openud_id
 * @property int|null $max_repost
 * @property int|null $max_like
 * @property int|null $max_follower
 * @property int|null $max_view
 * @property string|null $to_completed
 * @property string|null $from_completed
 * @property int|null $registered_data
 * @property int|null $last_login
 * @property int|null $tiktok_status
 * @property int|null $group_id
 * @property int|null $created_at
 * @property int|null $max_comment
 * @property string $password
 *
 * @property Action[] $actions
 * @property Group $group
 */
class TiktokAccount extends ActiveRecord
{
    const STATUS_ACTIVE = 1;
    const STATUS_INVALID = 2;
    const STATUS_AWAITING = 3;

    const BOT_STATUS_ACTIVE = 1;

    public $follower;


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%tiktok_account}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['email', 'device_id', 'fp', 'iid', 'openud_id', 'url'], 'required'],
            [['max_repost', 'max_like', 'max_view', 'max_follower', 'registered_data', 'last_login', 'tiktok_status', 'group_id', 'created_at', 'max_comment'], 'default', 'value' => null],
            [['max_repost', 'max_like', 'max_view', 'max_follower', 'registered_data', 'last_login', 'tiktok_status', 'group_id', 'created_at', 'max_comment'], 'integer'],
            [['nickname', 'secure_id', 'email', 'device_id', 'fp', 'iid', 'openud_id', 'password', 'tiktok_id'], 'string', 'max' => 255],
            [['url', 'uuid'], 'string', 'max' => 255],
            [['to_completed', 'from_completed'], 'string', 'max' => 5],
            [['email'], 'unique'],
            [['email'], 'email'],
            [['nickname', 'device_id', 'iid', 'openud_id',], 'unique'],
            [['url'], 'unique'],
            ['password', 'required', 'when' => function ($model) {
                return $model->isNewRecord;
            },
                'whenClient' => "function (attribute, value) {
                    return {$this->isNewRecord};
                }"
            ],
            [['nickname'], 'match', 'pattern' => '/^@[\w,\.,\-]*$/i'],
//            [['device_id'], 'match', 'pattern' => '/[^0-9]/'],
//            [['fp', 'iid','openud_id'], 'match', 'pattern' => '/^[A-Za-z0-9]+$/i'],
            [['group_id'], 'exist', 'skipOnError' => true, 'targetClass' => Group::class, 'targetAttribute' => ['group_id' => 'id']],
            [['from_completed', 'to_completed'], 'date', 'format' => 'H:m'],
            [['from_completed', 'to_completed'], 'validateTimeField'],
            ['url', 'common\validators\AccountValidator'],
            [['max_like', 'max_follower', 'max_view', 'max_repost'], 'number', 'min' => 1],
            [['max_like', 'max_follower', 'max_view', 'max_repost'], 'number', 'max' => 300],

        ];
    }

    public function validateTimeField($attribute)
    {
        $to_completed = strtotime($this->to_completed);
        $from_completed = strtotime($this->from_completed);

        if ($from_completed > $to_completed || $from_completed === $to_completed) {
            $this->addError($attribute, $this->getAttributeLabel('Неверно выбрано время'));
        }
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'nickname' => Yii::t('app', 'Никнейм'),
            'url' => Yii::t('app', 'Ссылка на аккаунт'),
            'secure_id' => Yii::t('app', 'Secure ID'),
            'email' => Yii::t('app', 'Email'),
            'password' => Yii::t('app', 'Пароль'),
            'device_id' => Yii::t('app', 'Device ID'),
            'fp' => Yii::t('app', 'Fp'),
            'iid' => Yii::t('app', 'Iid'),
            'openud_id' => Yii::t('app', 'Openud ID'),
            'max_repost' => Yii::t('app', 'Количество репостов'),
            'max_like' => Yii::t('app', 'Количество лайков'),
            'max_view' => Yii::t('app', 'Количество просмотров'),
            'max_follower' => Yii::t('app', 'Количество подписок'),
            'max_comment' => Yii::t('app', 'Количество комментариев'),
            'to_completed' => Yii::t('app', 'До'),
            'from_completed' => Yii::t('app', 'С'),
            'registered_data' => Yii::t('app', 'Registered Data'),
            'last_login' => Yii::t('app', 'Последняя авторизация'),
            'tiktok_status' => Yii::t('app', 'Статус'),
            'group_id' => Yii::t('app', 'Group ID'),
            'created_at' => Yii::t('app', 'Дата создания'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getActions()
    {
        return $this->hasMany(Action::class, ['tiktok_account_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroup()
    {
        return $this->hasOne(Group::class, ['id' => 'group_id']);
    }

    public static function getStatus(): array
    {
        return [
            self::STATUS_ACTIVE => Yii::t('app', 'Aктивный'),
            self::STATUS_INVALID => Yii::t('app', 'Невалидный'),
            self::STATUS_AWAITING => Yii::t('app', 'Ожидает'),
        ];
    }

    public function beforeValidate()
    {
        if ($this->from_completed == '00:00' || $this->to_completed == '00:00' || $this->from_completed == null || $this->to_completed == null) {
            $this->from_completed = Setting::FROM_COMPLETED;
            $this->to_completed = Setting::TO_COMPLETED;
        }
        return parent::beforeValidate();
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->created_at = time();
        }
        if ($this->max_like == null) {
            $this->max_like = Setting::MAX_LIKE;
        }
        if ($this->max_follower == null) {
            $this->max_follower = Setting::MAX_SUBSCRIBE;
        }
        if ($this->max_view == null) {
            $this->max_view = Setting::MAX_VIEW;
        }


        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            $this->addAccountOnTikTOk($this, ActionManager::ACCOUNT_URL, 'POST');
        }

    }

    public static function getAccounts()
    {
        return yii\helpers\ArrayHelper::map(self::find()->where(['tiktok_status' => self::STATUS_ACTIVE])->all(), 'id', 'nickname');
    }


    public function addAccountOnTikTOk($account, $url, $method)
    {
        if ($account) {
            $sentData = [
                "email" => $account->email,
                "pass" => $account->password,
                "device_id" => $account->device_id,
                "fp" => $account->fp,
                "iid" => $account->iid,
                "openudid" => $account->openud_id,
            ];
            if ($account->uuid) {
                $sentData['uuid'] = $account->uuid;
            }

            $response = ActionManager::send($sentData, $url, $method);
            if ($response && isset($response['uuid'])) {

                Yii::$app->db->createCommand()
                    ->update('tiktok_account', [
                        'uuid' => $response['uuid'],
                        'tiktok_status' => self::STATUS_AWAITING],
                        ['id' => $this->id])
                    ->execute();

            }
        }
    }


    public function afterDelete()
    {

        if ($this->uuid) {
            $sentData['uuid'] = $this->uuid;

            ActionManager::send($sentData, ActionManager::ACCOUNT_URL, 'DELETE');
        }

        parent::afterDelete();
    }


    public static function check($account)
    {
        if ($account->uuid) {
            $sentData = [
                "uuid" => $account->uuid,
            ];

            $responseData = ActionManager::send($sentData, ActionManager::ACCOUNT_CHECK_URL, 'GET');

            if ($responseData && isset($responseData['is_active'])) {

                ActionManager::changeUserStatus($account->id, $responseData['is_active'] );

                if ($responseData['is_active'] == self::STATUS_ACTIVE) {
                    ActionManager::changeLastAuth($account->id);
                }
            }


        }

    }


}

backend/controllers/TiktokAccountController.php
<?php

namespace backend\controllers;

use backend\forms\import\CsvImportForm;
use backend\services\ActionManager;
use Yii;
use common\models\TiktokAccount;
use common\models\search\TiktokAccountSearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use \yii\web\ServerErrorHttpException;

/**
 * TiktokAccountController implements the CRUD actions for TiktokAccount model.
 */
class TiktokAccountController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'view','import'],
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all TiktokAccount models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TiktokAccountSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TiktokAccount model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TiktokAccount model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TiktokAccount();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing TiktokAccount model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $oldAttributes = $model->oldAttributes;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            $isChange = $model->attributes == $oldAttributes;
            if (!$isChange) {
                $model->addAccountOnTikTOk($model, ActionManager::ACCOUNT_URL, 'PATCH');
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing TiktokAccount model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        try {
            $this->findModel($id)->delete();
        } catch (\Exception $e) {
            throw new ServerErrorHttpException(Yii::t('app',
                'Невозможно удалить аккаунт, так как к ней привязаны действия.'));
        }

        return $this->redirect(['index']);
    }

    public function actionImport()
    {
        $model = new CsvImportForm();
        $model->file = UploadedFile::getInstance($model, 'file');

        if ($model->file) {
            $csvFile = $model->upload( \Yii::getAlias('@csv-accounts'));

            if ($csvFile) {
                $accounts = $model->importAccountData($csvFile);
                Yii::$app->session->setFlash('info', \Yii::t(
                    'app',
                    '{n, plural, =0{Добавлено # аккаунтов} one{Добавлен # аккаунт} few{Добавлено # аккаунта} other{Добавлено # аккаунтов}}',
                    ['n' =>  count($accounts)]
                ));
            }

        }
        $this->redirect('index');
    }


    /**
     * Finds the TiktokAccount model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TiktokAccount the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TiktokAccount::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }


}

backend/views/tiktok-account/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\time\TimePicker;
use  \common\models\Setting;

/* @var $this yii\web\View */
/* @var $model common\models\TiktokAccount */
/* @var $form yii\widgets\ActiveForm */

?>
<style>
    #custom_graph {
        display: none;
    }
</style>
<div class="tiktok-account-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php if (!$model->isNewRecord): ?>
        <?= $form->field($model, 'nickname')->textInput(['maxlength' => true, 'disabled' => true]) ?>
    <?php endif; ?>

    <?= $form->field($model, 'url')->textInput(['maxlength' => true, 'disabled' => !$model->isNewRecord,'autocomplete' => 'off']) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true, 'autocomplete' => 'off']) ?>

    <?= $form->field($model, 'password')->textInput(['maxlength' => true, 'autocomplete' => 'off']) ?>

    <?= $form->field($model, 'device_id')->textInput(['maxlength' => true, 'autocomplete' => 'off']) ?>

    <?= $form->field($model, 'fp')->textInput(['maxlength' => true, 'autocomplete' => 'off']) ?>

    <?= $form->field($model, 'iid')->textInput(['maxlength' => true,'autocomplete' => 'off']) ?>

    <?= $form->field($model, 'openud_id')->textInput(['maxlength' => true, 'autocomplete' => 'off']) ?>

    <p class="label_bold"><?= Yii::t('app', 'Лимиты на действия аккаунта в сутки') ?></p>

    <?= $form->field($model, 'max_repost')->textInput(['placeholder' => Yii::t('app', 'Введите максимальное число')]) ?>

    <?= $form->field($model, 'max_like')->textInput(['placeholder' => Yii::t('app', 'Введите максимальное число')]) ?>

    <?= $form->field($model, 'max_view')->textInput(['placeholder' => Yii::t('app', 'Введите максимальное число')]) ?>

    <?= $form->field($model, 'max_follower')->textInput(['placeholder' => Yii::t('app', 'Введите максимальное число')]) ?>

    <div id="schedule_type">
        <p class="label_bold"><?= Yii::t('app', 'График выполнения действии') ?></p>
        <div class="bottom-10"><input type="radio" name="schedule_type" value="0">
            <span class="schedule_label">
            <?= Yii::t('app', 'По стандарту: (') . Setting::FROM_COMPLETED . ' - ' . Setting::TO_COMPLETED . ')' ?>
        </span>
        </div>
        <div class="bottom-10">
            <input type="radio" name="schedule_type" value="1">
            <span class="schedule_label"><?= Yii::t('app', 'Задать своё ') ?></span>
        </div>
    </div>
    <div id="custom_graph" <?= $model->to_completed != '00:00' && $model->from_completed != '00:00' ? 'style="display:block"' : '' ?>>
        <div class="row">
            <div class="col-md-4">
                <?= $form->field($model, 'from_completed')->widget(TimePicker::class,
                    [
                        'pluginOptions' => [
                            'showMeridian' => false,
                            'allowClear' => true,
                            'defaultTime' => '',
                        ],
                    ]); ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'to_completed')->widget(TimePicker::class,
                    [
                        'pluginOptions' => [
                            'showMeridian' => false,
                            'allowClear' => true,
                            'defaultTime' => '',
                        ]
                    ]); ?>
            </div>
        </div>
        <p style="display: none" id="shc_error" class="help-block"><?= Yii::t('app', 'Выберите график ') ?>
    </div>
    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Сохранить'), ['class' => 'btn btn-success create-accounts']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

<?php
$script = <<< JS

$('form').submit(function () {

    var schedule_type = $("#schedule_type input[type=radio]:checked").val();
    if (schedule_type == 0) {
        $('#shc_error').hide();
        $('#tiktokaccount-from_completed').val('00:00');
        $('#tiktokaccount-to_completed').val('00:00');
        return true;
    } else if (schedule_type == 1) {
       var from =   $('#tiktokaccount-from_completed').val();
      var to =  $('#tiktokaccount-to_completed').val();
     
      if(from == '00:00' || to == '00:00'){
          $('#shc_error').show();
          return false;
      }else{
            $('#shc_error').hide();
             return true;
      }
        
    }

});

JS;
$this->registerJs($script, \yii\web\View::POS_READY);
?>

backend/views/tiktok-account/_import.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use \yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\TiktokAccount */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="import-form">

    <?php $form = ActiveForm::begin(['id' => 'import-csv', 'action' => Url::to('/tiktok-account/import')]); ?>

    <div class="row">
        <div class="col-md-8">
            <?=
            $form->field($model, 'file')->widget(FileInput::class, [
                'options' => ['multiple' => false],
                'pluginOptions' => [
                    'showPreview' => false,
                    'showCaption' => true,
                    'showCancel' => false,
                    'showRemove' => false,
                    'showUpload' => false,
                    'placeholder' => false,
                ]
            ])->label(false);

            ?>
            <p class="i-message"><?= Yii::t('app', 'Разрешена загрузка файла только с расширением CSV (разделитель - запятая). 
            Первая строка обязательно должна содержать заголовки: Ссылка на аккаунт, Email, Пароль, Device ID, Fp, Iid, Openud ID') ?></p>
        </div>
        <div class="col-md-4  form-group">
            <?= Html::submitButton(Yii::t('app', 'Загрузить'), ['class' => 'import-btn btn btn-dark']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/tiktok-account/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\TiktokAccountSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="tiktok-account-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nickname') ?>

    <?= $form->field($model, 'url') ?>

    <?= $form->field($model, 'secure_id') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'password') ?>

    <?php // echo $form->field($model, 'device_id') ?>

    <?php // echo $form->field($model, 'fp') ?>

    <?php // echo $form->field($model, 'iid') ?>

    <?php // echo $form->field($model, 'openud_id') ?>

    <?php // echo $form->field($model, 'max_repost') ?>

    <?php // echo $form->field($model, 'max_like') ?>

    <?php // echo $form->field($model, 'max_follower') ?>

    <?php // echo $form->field($model, 'to_completed') ?>

    <?php // echo $form->field($model, 'from_completed') ?>

    <?php // echo $form->field($model, 'registered_data') ?>

    <?php // echo $form->field($model, 'last_login') ?>

    <?php // echo $form->field($model, 'tiktok_status') ?>

    <?php // echo $form->field($model, 'group_id') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/tiktok-account/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\TiktokAccount */

$this->title = Yii::t('app', 'Добавить Аккаунт');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Tiktok Accounts'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="tiktok-account-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/tiktok-account/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use kartik\date\DatePicker;
use \common\models\TiktokAccount;
use  \common\components\grid\ActionColumn;
use \backend\forms\import\CsvImportForm;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\TiktokAccountSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Аккаунты');
$this->params['breadcrumbs'][] = $this->title;
$import = new CsvImportForm();
?>
<div class="tiktok-account-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-md-2">
            <p>
                <?= Html::a(Yii::t('app', 'Добавить'), ['create'], ['class' => 'btn btn-success btn-proxi']) ?>
            </p>
        </div>
        <div class="col-md-6">
            <?= $this->render('_import', ['model' => $import]); ?>
        </div>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'nickname',
            [
                'attribute' => 'created_at',
                'format' => ['date', 'dd.MM.Y'],
                'filter' => DatePicker::widget([
                    'model' => $searchModel,
                    'value' => $searchModel->created_at,
                    'attribute' => 'created_at',
                    'pluginOptions' => [
                        'orientation' => 'bottom'
                    ]
                ]),
            ],
            [
                'attribute' => 'last_login',
                'format' => ['date', 'dd.MM.Y'],
                'filter' => DatePicker::widget([
                    'model' => $searchModel,
                    'value' => $searchModel->last_login,
                    'attribute' => 'last_login',
                    'pluginOptions' => [
                        'orientation' => 'bottom'
                    ]
                ]),
            ],
            [
                'attribute' => 'tiktok_status',
                'filter' => TiktokAccount::getStatus(),
                'value' => function ($model) {
                    return $model->tiktok_status ? TiktokAccount::getStatus()[$model->tiktok_status] : '';
                }
            ],
            [
                'class' => ActionColumn::class,
                'contentOptions' => ['class' => 'action-column'],
            ],

        ],
    ]); ?>

</div>

backend/views/tiktok-account/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\TiktokAccount */

$this->title = Yii::t('app', 'Редактировать аккаунт: ' . $model->nickname, [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Tiktok Accounts'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="tiktok-account-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/tiktok-account/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use common\models\TiktokAccount;

/* @var $this yii\web\View */
/* @var $model common\models\TiktokAccount */

$this->title = $model->nickname;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Tiktok Accounts'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="tiktok-account-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Редактировать'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Удалить'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' =>  Yii::t('app','Вы действительно хотите удалить?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nickname',
            'email:email',
            'url:url',
            'uuid',
            'secure_id',
            'tiktok_id',
            'device_id',
            'fp',
            'iid',
            'openud_id',
            'max_repost',
            'max_like',
            'max_view',
            'max_follower',
            'max_comment',
            'from_completed',
            'to_completed',
            'last_login',
            [
                'attribute' => 'tiktok_status',
                'value' => function ($model) {
                    return $model->tiktok_status ? TiktokAccount::getStatus()[$model->tiktok_status] : '';
                }
            ],
            [
                'attribute' => 'created_at',
                'format' => ['date', 'php:d.m.Y'],
            ],
        ],
    ]) ?>

</div>