common/models/Proxy.php
<?php

namespace common\models;

use backend\services\ProxyCheckerService;
use common\components\parser\LoadException;
use Yii;
use yii\web\NotFoundHttpException;
use \yii\db\ActiveRecord;

/**
 * This is the model class for table "proxi".
 *
 * @property int $id
 * @property int $login
 * @property int $password
 * @property int $IP
 * @property int $port
 * @property string|null $check_date
 * @property int $status
 * @property int $last_used_date
 * @property string|null $error_message
 */
class Proxy extends ActiveRecord
{

    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 2;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%proxi}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['login', 'password', 'IP', 'port'], 'required'],
            [['IP'], 'unique'],
            ['IP', 'ip'],
            [['login', 'password', 'IP', 'port', 'status', 'last_used_date'], 'default', 'value' => null],
            [['check_date', 'error_message', 'login', 'password', 'IP', 'port'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'login' => Yii::t('app', 'Логин'),
            'password' => Yii::t('app', 'Пароль'),
            'IP' => Yii::t('app', 'IP'),
            'port' => Yii::t('app', 'Порт'),
            'check_date' => Yii::t('app', 'Последняя проверка'),
            'status' => Yii::t('app', 'Статус   '),
            'error_message' => Yii::t('app', 'Сообщение'),
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->status = self::STATUS_INACTIVE;
        }

        return parent::beforeSave($insert);
    }

    public static function getStatus()
    {
        return [
            self::STATUS_ACTIVE => Yii::t('app', 'Активный'),
            self::STATUS_INACTIVE => Yii::t('app', 'Неактивный'),
        ];
    }

    public function getActive()
    {
        $proxy = Proxy::find()
            ->where(['status' => Proxy::STATUS_ACTIVE])
            ->orderBy(['last_used_date' => SORT_ASC])
            ->one();
        if ($proxy) {
            $proxyChecker = new ProxyCheckerService();
            $address = $proxy->IP . ':' . $proxy->port;

            $content = $proxyChecker->getProxyContent($address, $proxy->login, $proxy->password);

            if ($content) {
                $proxy->last_used_date = strtotime(date("Y-m-d H:i:s"));
                $proxy->save();
                return $proxy;
            } else {
                $proxy->status = self::STATUS_INACTIVE;
                $proxy->check_date = date("Y-m-d H:i:s");
                $proxy->last_used_date = strtotime(date("Y-m-d H:i:s"));
                $proxy->save();
            }
        } else {
            Yii::$app->session->setFlash('error', Yii::t('app', 'Нет активных прокси'));
            throw new NotFoundHttpException(Yii::t('app', 'Нет  активных прокси'));
        }

        return $this->getActive();

    }

}

backend/controllers/ProxyController.php
<?php

namespace backend\controllers;

use backend\forms\import\CsvImportForm;
use backend\services\ProxyCheckerService;
use Yii;
use common\models\Proxy;
use common\models\search\ProxySearch;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ProxyController implements the CRUD actions for Proxy model.
 */
class ProxyController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update', 'delete', 'view', 'import'],
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    /**
     * Lists all Proxy models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProxySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Proxy model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Proxy model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Proxy();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Proxy model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Proxy model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Proxy model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Proxy the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Proxy::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }


    public function actionImport()
    {
        $model = new CsvImportForm();
        $model->file = UploadedFile::getInstance($model, 'file');

        if ($model->file) {
            $csvFile = $model->upload(\Yii::getAlias('@csv-proxy'));

            if ($csvFile) {
                $proxy = $model->importProxyData($csvFile);
                Yii::$app->session->setFlash('info', Yii::t('app', 'Добавлено '. count($proxy). ' прокси.'));
            }

        }
        $this->redirect('index');
    }

}

backend/views/proxy/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Proxy */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="Proxy-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'login')->textInput(['autocomplete' => 'off']) ?>

    <?= $form->field($model, 'password')->textInput(['autocomplete' => 'off']) ?>

    <?= $form->field($model, 'IP')->textInput(['autocomplete' => 'off']) ?>

    <?= $form->field($model, 'port')->textInput(['autocomplete' => 'off']) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Сохранить'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/proxy/_import.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use \yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Proxy */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="import-form">

    <?php $form = ActiveForm::begin(['id' => 'import-csv', 'action' => Url::to('/proxy/import')]); ?>

    <div class="row">
        <div class="col-md-8">
            <?= $form->field($model, 'file')->widget(FileInput::class, [
                'options' => ['multiple' => false],
                'pluginOptions' => [
                    'showPreview' => false,
                    'showCaption' => true,
                    'showCancel' => false,
                    'showRemove' => false,
                    'showUpload' => false,
                    'placeholder' => false,
                ]
            ])->label(false);
            ?>
            <p class="i-message"><?= Yii::t('app','Разрешена загрузка файла только с расширением CSV (разделитель - запятая). Первая строка обязательно должна содержать заголовки: логин, пароль, IP, хост') ?></p>
        </div>
        <div class="col-md-4  form-group">
            <?= Html::submitButton(Yii::t('app', 'Загрузить'), ['class' => 'import-btn btn btn-dark']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/proxy/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\ProxySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="Proxy-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'login') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'IP') ?>

    <?= $form->field($model, 'port') ?>

    <?php // echo $form->field($model, 'check_date') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'error_message') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/proxy/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Proxy */

$this->title = Yii::t('app', 'Создание прокси');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Proxys'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="Proxy-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/proxy/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use  \common\components\grid\ActionColumn;
use backend\forms\import\CsvImportForm;
use \common\models\Proxy;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\ProxySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Прокси');
$this->params['breadcrumbs'][] = $this->title;
$import = new CsvImportForm();
?>
<div class="Proxy-index">

    <h1><?= Html::encode($this->title) ?></h1>


    <div class="row">
        <div class="col-md-2">
            <p>
                <?= Html::a(Yii::t('app', 'Добавить'), ['create'], ['class' => 'btn btn-success btn-Proxy']) ?>
            </p>
        </div>
        <div class="col-md-6">
            <?= $this->render('_import', ['model' => $import]); ?>
        </div>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            [
                'label' => Yii::t('app', 'Адрес '),
                'value' => function ($model) {
                    return $model->login . '@' . $model->IP . '.' . $model->port;
                }
            ],
            'check_date',
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    return  $model->status ? Proxy::getStatus()[$model->status] : null;
                }
            ],
            [
                'class' => ActionColumn::class,
                'contentOptions' => ['class' => 'action-column'],
                'visibleButtons' => [
                    'delete' => function($model){
                        return $model->status == Proxy::STATUS_ACTIVE ? false : true;
                    },
                ],
            ],
        ],

    ]); ?>

</div>

backend/views/proxy/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Proxy */

$this->title = Yii::t('app', 'Редактирование: {name}', [
    'name' => $this->title = $model->IP . ':' . $model->port,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Proxys'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="Proxy-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/proxy/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use \common\models\Proxy;

/* @var $this yii\web\View */
/* @var $model common\models\Proxy */

$this->title = $model->IP . ':' . $model->port;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Proxys'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="Proxy-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Редактировать'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Удалить'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Вы действительно хотите удалить?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'login',
            'password',
            'IP',
            'port',
            'check_date',
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    return $model->status ? Proxy::getStatus()[$model->status] : null;
                }
            ],
        ],
    ]) ?>

</div>